version: '3.0'
services:
  nestapp:
    container_name: AUTHAPP
    image: ghanem/auth-app
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    environment:
      - DB_TYPE=postgres
      - DB_USER=myuser
      - DB_PASSWORD=mypass
      - DB_NAME=mydb
      - DB_PORT=5432
      - DB_HOST=db
    depends_on:
      - db
  db:
 
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
      # Where our data will be persisted
    volumes:
      - db:/var/lib/postgres
# Names our volume
volumes:
  db: